{"result": {"history_size": 1, "folders": ["lab4"], "nr": 1509, "data": {"embed_links": []}, "created": "2020-11-06T11:49:42Z", "bucket_order": 3, "no_answer_followup": 0, "change_log": [{"anon": "no", "uid": "k8zy4tivdrb74w", "data": "kh675a2tl9042l", "v": "all", "type": "create", "when": "2020-11-06T11:49:42Z"}], "bucket_name": "Today", "history": [{"anon": "no", "uid": "k8zy4tivdrb74w", "subject": "make debug的时候出现Cannot find bounds of current function", "created": "2020-11-06T11:49:42Z", "content": "<md>对于lab5实验，想完整走一遍流程，结果make debug之后断点的位置是正确的，但是一旦输入next就出现Cannot find bounds of current function\nvim tools/gdbinit如下：\n\n```\nfile bin/kernel\ntarget remote :1234\nbreak kern_init\n```</md>"}], "type": "question", "tags": ["lab4", "student", "unanswered"], "tag_good": [], "unique_views": 138, "children": [], "tag_good_arr": [], "no_answer": 1, "id": "kh675a2ruw942k", "config": {"seen": {"881": 5, "145": 0, "125": 8, "743": 4, "997": 1, "1056": 6, "161": 3, "1292": 2, "1192": 7}}, "status": "active", "drafts": null, "request_instructor": 0, "request_instructor_me": false, "bookmarked": 1, "num_favorites": 0, "my_favorite": false, "is_bookmarked": false, "is_tag_good": false, "q_edits": [], "i_edits": [], "s_edits": [], "t": 1643170241459, "default_anonymity": "no"}, "error": null, "aid": "kyv14wqbajj65e"}