{"result": {"history_size": 1, "folders": ["工具使用", "lab1"], "nr": 636, "data": {"embed_links": []}, "created": "2016-02-29T09:39:58Z", "bucket_order": 3, "no_answer_followup": 0, "change_log": [{"uid": "i14g50r7ui12pn", "anon": "no", "when": "2016-02-29T09:39:58Z", "data": "il7so2j1g60eq", "type": "create"}, {"to": "il7so2iy2c9ep", "uid": "i6w84pnmjCQ", "anon": "no", "when": "2016-02-29T13:07:21Z", "type": "followup"}, {"to": "il7so2iy2c9ep", "uid": "i0et95bli7r7ky", "anon": "no", "when": "2016-02-29T13:34:06Z", "type": "followup"}], "bucket_name": "Today", "history": [{"anon": "no", "uid": "i14g50r7ui12pn", "subject": "无法push到gitlab&#xff1a;“ ! [remote rejected] master -&gt; master (pre-receive hook declined)    ”", "created": "2016-02-29T09:39:58Z", "content": "<p>无论是docker的webshell还是自己连vpn&#xff0c;在使用git push命令时都会遇到失败&#xff1a;</p>\n<pre>Warning: Permanently added &#39;172.16.13.236&#39; (ECDSA) to the list of known hosts.                                                            \nCounting objects: 3, done.                                                                                                                \nWriting objects: 100% (3/3), 204 bytes | 0 bytes/s, done.                                                                                 \nTotal 3 (delta 0), reused 0 (delta 0)                                                                                                     \nremote: GitLab: The project you were looking for could not be found.                                                                      \nTo git&#64;172.16.13.236:cherudim9/ucore_lab.git                                                                                              \n ! [remote rejected] master -&gt; master (pre-receive hook declined)                                                                         \nerror: failed to push some refs to &#39;git&#64;172.16.13.236:cherudim9/ucore_lab.git&#39;  </pre>\n<p>按照往年的帖子&#xff0c;还有网上的解答&#xff0c;试图通过修改project setting中的protect_branch&#xff0c;但是没法进入这个页面&#xff0c;会直接转到project的首页。。</p>"}], "type": "question", "tags": ["lab1", "student", "unanswered", "工具使用"], "tag_good": [{"role": "student", "name": "Long Haomin", "endorser": {}, "admin": false, "photo": null, "id": "i14g50r7ui12pn", "photo_url": null, "published": true, "us": false, "class_sections": ["课程设计_i5j09fnsl7k5x0", "清华学生_i5j09fnsl7k5x0"], "facebook_id": null}], "unique_views": 141, "children": [{"anon": "no", "folders": [], "data": {"embed_links": null}, "no_upvotes": 0, "subject": "<p></p>\n<p>&#43;1&#xff0c;按照下面这个的说法</p>\n<p>http://stackoverflow.com/questions/7986139/git-error-when-trying-to-push-pre-receive-hook-declined</p>\n<p>可能是因为助教还没修好服务器所以拒绝了&#xff1f;求解释</p>", "created": "2016-02-29T13:07:21Z", "bucket_order": 275, "bucket_name": "Week 2/28 - 3/5", "type": "followup", "tag_good": [], "uid": "i6w84pnmjCQ", "children": [], "tag_good_arr": [], "no_answer": 0, "id": "il802re0qsr34h", "updated": "2016-02-29T13:07:21Z", "config": {}}, {"anon": "no", "folders": [], "data": {"embed_links": null}, "no_upvotes": 0, "subject": "<p>&#43;1 遇到一样的问题</p>", "created": "2016-02-29T13:34:06Z", "bucket_order": 275, "bucket_name": "Week 2/28 - 3/5", "type": "followup", "tag_good": [], "uid": "i0et95bli7r7ky", "children": [], "tag_good_arr": [], "no_answer": 0, "id": "il8115tjyc1bm", "updated": "2016-02-29T13:34:06Z", "config": {}}], "tag_good_arr": ["i14g50r7ui12pn"], "no_answer": 1, "id": "il7so2iy2c9ep", "config": {}, "status": "active", "drafts": null, "request_instructor": 0, "request_instructor_me": false, "bookmarked": 5, "num_favorites": 0, "my_favorite": false, "is_bookmarked": false, "is_tag_good": false, "q_edits": [], "i_edits": [], "s_edits": [], "t": 1643168211796, "default_anonymity": "no"}, "error": null, "aid": "kyuzxems1qy8k"}